### ISSUE TITLE
Something strange happening

### ISSUE THREAD

**Issue by afedukov** [JosephSilber/page-cache#110]
Strange issue: sometimes, on my cached pages ALL links are replaced with some random string or domain, that of course breaks the website. Anyone experienced that behavior?

**Comment by ahinkle** [comment]
Have you ever encountered a situation where the entire domain (e.g., links, images) are swapped with a different domain on a specific page? I encountered this today.

**Comment by JosephSilber** [comment]
Do you have any other entry into your app, by a different domain?

Whatever is rendered the first time the page is encountered, that's what gets cached to disk.

**Comment by JosephSilber** [comment]
Laravel's `url` helper (and friends) generally use the `APP_URL` variable in your `env` to build URLs. If some pages are accessed with that `env` variable being something, then that's what will be cached for future requests.

**Comment by ahinkle** [comment]
Yeah, do you have any security recommendations that we could have missed? 

We have an L11 app that is very minimal up on Forge.  The client can be considered a possible high target. We found that the `public/page-cage/index.html` file was deliberately modified in logs to a different URL.  I understand that the scope can be outside of this package here, but I just want to ensure we didn't miss any security recommendations since it's in the /public/ realm.
