### ISSUE TITLE
How to set ttl time

### ISSUE THREAD

**Issue by Romoloso** [JosephSilber/page-cache#75]
if I want to set the page expired after 10 minutes, How should I do?

**Comment by JosephSilber** [comment]
Since files are cached directly on disk, there's no built-in TTL.

You can easily add [a schedule](https://laravel.com/docs/8.x/scheduling#defining-schedules) that calls `php artisan page-cache:clear` every 10 minutes:

```php
$schedule->command('page-cache:clear')->everyTenMinutes();
```

While not exactly the same as a TTL, it'll ensure that nothing is ever cached for longer than 10 minutes.

**Comment by Romoloso** [comment]
@JosephSilber thank you, that's a good idea! I closed the issue
